# Name:- Parshwa Shah
# Experiment No.:- 4
# Roll No.- 34
# UID:- 2019230071
# Batch:- B

<h2>Aim:- To perform hypothesis testing on a dataset </h2>

<h3><center>Analyze statistical data using Python</center></h3>

<h3>Importing the libraries </h3>

In [1]:
import pandas as pd

<h3>Download the employee attrition dataset </h3>

In [2]:
! gdown --id 1SyCHwkwHRNCJrIxfKcL_vAhBPBEcc1xY

Downloading...
From: https://drive.google.com/uc?id=1SyCHwkwHRNCJrIxfKcL_vAhBPBEcc1xY
To: /content/WA_Fn-UseC_-HR-Employee-Attrition.csv
100% 228k/228k [00:00<00:00, 2.04MB/s]


<h3>Load the dataset </h3>

In [3]:
dataset = pd.read_csv('./WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [4]:
dataset

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

<h3>Get total columns in dataset </h3>

In [5]:
dataset.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

<h3>Perform One-Sample T-Test on age of employees </h3>

<h4>One Sample T-Test <br/>

H0: Average age of employees is 30 <br/>

H1: Average age of employees is not 30<br/></h4>

In [6]:
from scipy.stats import ttest_1samp
import numpy as np
ages = dataset.iloc[:,0].values
ages_mean = np.mean(ages)
print("Average age=",ages_mean)
tset, pval = ttest_1samp(ages, 30)
print("p-values",pval)
if pval < 0.05:    # alpha value is 0.05 or 5%
   print("Rejecting null hypothesis")
else:
  print("Accepting null hypothesis")

Average age= 36.923809523809524
p-values 4.679915477144685e-147
Rejecting null hypothesis


<h4>Inference: Since, the average age of employees is not 30 so null hypothesis is rejected</h4>

<h3>Perform ANOVA test on different Education fields of employees with respect to attrition </h3>

<h4>Design the ANOVA dataset </h4>

In [7]:
from scipy import stats
df_anova = dataset[['Attrition','EducationField']]

<h4>Perform LabelEncoding on Attrition column </h4>

In [8]:
from sklearn import preprocessing
 
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
 
# Encode labels in column 'species'.
df_anova['Attrition']= label_encoder.fit_transform(df_anova['Attrition'])
 
df_anova['Attrition'].unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


array([1, 0])

<h4>ANOVA Test <br/>

H0: People of Education Field : Life Sciences, Medical and Human Resources have similar Attrition characteristics <br/>

H1: People of Education Field : Life Sciences, Medical and Human Resources do not have similar Attrition characteristics<br/></h4>

In [9]:
grps = pd.unique(df_anova.EducationField.values)
d_data = {grp:df_anova['Attrition'][df_anova.EducationField == grp] for grp in grps}
F, p = stats.f_oneway(d_data['Life Sciences'], d_data['Medical'], d_data['Human Resources'])
print("p-value for significance is: ", p)
print("F value is",F)
if p<0.05:
    print("Reject null hypothesis")
else:
    print("Accept null hypothesis")

p-value for significance is:  0.20437148779805528
F value is 1.5901226873042957
Accept null hypothesis


<h4>Inference: From the results of ANOVA test, we can say that employees of  Education fields like Life Sciences, Medical and Human Resources have similar Attrition characteristics </h4>

<h3>Perform Chi Square test to check association between Employee WorkLifeBalance and Attrition </h3>

<h4>Design Chi Square Data </h4>

In [10]:
chi_data = dataset[['WorkLifeBalance','Attrition']]

In [11]:
chi_data

WorkLifeBalance Attrition
0                   1       Yes
1                   3        No
2                   3       Yes
3                   3        No
4                   3        No
...               ...       ...
1465                3        No
1466                3        No
1467                3        No
1468                2        No
1469                4        No

[1470 rows x 2 columns]

<h4> Check descriptive statistics </h4>

In [12]:
chi_data.describe()

WorkLifeBalance
count      1470.000000
mean          2.761224
std           0.706476
min           1.000000
25%           2.000000
50%           3.000000
75%           3.000000
max           4.000000

<h4>Chi Square Test <br/>

H0: WorkLifeBalance and Attrttion are not associated <br/>

H1: WorkLifeBalance and Attrttion are associated<br/></h4>

<h4> Explore Contingency Table </h4>

WorkLifeBalance

1.   Bad
2.   Good
3.   Better
4.   Best



Attrition

Yes.   Employee left the company <br>
No.    Employee remained in the company



In [13]:
contingency_table=pd.crosstab(chi_data["WorkLifeBalance"],chi_data["Attrition"])
contingency_table

Attrition         No  Yes
WorkLifeBalance          
1                 55   25
2                286   58
3                766  127
4                126   27

<h4> Display the observed values </h4>

In [14]:
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[ 55  25]
 [286  58]
 [766 127]
 [126  27]]


<h4> Apply Chi-Square test and get
 </h4>

1.   Chi Square Statistic value
2.   p value
3.   Degree of freedom value
4.   Expected values



In [15]:
from scipy.stats import chi2_contingency
chi_square_statistic, p, dof, Expected_Values = chi2_contingency(contingency_table)

In [16]:
chi_square_statistic

16.3250970916474

In [17]:
p

0.0009725698845348824

In [18]:
dof

3

In [19]:
Expected_Values

array([[ 67.10204082,  12.89795918],
       [288.53877551,  55.46122449],
       [749.02653061, 143.97346939],
       [128.33265306,  24.66734694]])

<h4> Define Level of Significance alpha and get critical value </h4>

In [20]:
alpha = 0.05

In [21]:
from scipy.stats import chi2
critical_value=chi2.ppf(q=1-alpha,df=dof)
print('critical_value:',critical_value)

critical_value: 7.814727903251179


<h4> Print all values of Chi-Square test </h4>

In [22]:
print('Significance level: ',alpha)
print('Degree of Freedom: ',dof)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p)

Significance level:  0.05
Degree of Freedom:  3
chi-square statistic: 16.3250970916474
critical_value: 7.814727903251179
p-value: 0.0009725698845348824


<h4> Get the results of the test </h4>

In [23]:
if chi_square_statistic>=critical_value:
    print("Reject H0, there is a relationship between WorkLifeBalance and Attrition")
else:
    print("Retain H0, there is no relationship between WorkLifeBalance and Attrition")
    
if p<=alpha:
    print("Reject H0, there is a relationship between WorkLifeBalance and Attrition")
else:
    print("Retain H0, there is no relationship between WorkLifeBalance and Attrition")

Reject H0, there is a relationship between WorkLifeBalance and Attrition
Reject H0, there is a relationship between WorkLifeBalance and Attrition


<h4>Inference: From the results of Chi square test, we can say that WorkLifeBalance in employee's life affects attrition. If employee has better work life balance, then there are less chances of attrition i.e. employee leaving the company </h4>

<h3>Conclusion: Hence, from this experiment, I understood the concepts of hypothesis testing and statistics. Also, I applied these concepts on Employee Attrition dataset. I performed 3 tests: 1) One sample T-test 2) ANOVA test 3) Chi Square test for hypothesis tesing and also finding whether to accept or reject null hypothesis. </h3>